### ISSUE TITLE
Cannot seem to build on Ubuntu 20.04

### ISSUE THREAD

**Issue by nolanlawson** [kevinsung/slp-to-video#10]
Hey, this tool looks really nice. I tried to get it to work on Ubuntu 20.04, though, and I ran into several errors like this (from `CMakeError.log`):

```
/slp-to-video/Ishiiruka/build/CMakeFiles/CheckIncludeFiles/USE_AUDIOTRACK.c:2:10: fatal error: android/log.h: No such file or directory
    2 | #include <android/log.h>
      |          ^~~~~~~~~~~~~~~
...
/slp-to-video/Ishiiruka/build/CMakeFiles/CheckIncludeFiles/USE_SNDIO.c:2:10: fatal error: sndio.h: No such file or directory
    2 | #include <sndio.h>
      |          ^~~~~~~~~
...
/slp-to-video/Ishiiruka/build/CMakeFiles/CheckIncludeFiles/USE_KAI.c:2:10: fatal error: kai.h: No such file or directory
    2 | #include <kai.h>
      |          ^~~~~~~
```

I have Node 14.18.2, ffmpeg 4.2.4, and npm 6.14.15. I also installed all the deps from [here](https://github.com/project-slippi/Slippi-FM-installer#ubuntu-2004-lts) and [here](https://wiki.dolphin-emu.org/index.php?title=Building_Dolphin_on_Linux#18.04_LTS_and_up). It looks like maybe there's still some other dependency I'm missing, though?

**Comment by kevinsung** [comment]
Can you check if you are able to build https://github.com/project-slippi/Ishiiruka, following their instructions?
